<div class="section">
    <div class="row">
        <div class="small-6 columns">
            <h1><i class="fa fa-users"></i> PIN Rest <small></small></h1>
        </div>
        <div class="small-6 columns text-right">
            <ul class="button-group round">
                <li><a class="button secondary" href="<?php echo $this->link(array('accounts','inactive')) ?>">Back</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns text-center">
            <h2 class="subheader">New PIN: <?php echo $this->tempPin ?></h2>
        </div>
    </div>
</div>