<div class="row">
    <?php
    if(count($this->errorMessage) > 0)
    {

        echo "<div data-alert class=\"alert-box warning\">";
        foreach($this->errorMessage as $message)
        {
            echo $message;
        }
        echo "<a href=\"#\" class=\"close\">&times;</a></div>";

    }

    if(count($this->successMessage) > 0)
    {

        echo "<div data-alert class=\"alert-box success\">";
        foreach($this->successMessage as $message)
        {
            echo $message;
        }
        echo "<a href=\"#\" class=\"close\">&times;</a></div>";

    }
    ?>
</div>
<div class="row hide-for-print">
    <?php echo $this->formstart(); ?>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['date'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['inTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['outTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['lessTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['code'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <br>
        <?php echo $this->fields['submit'] ?>

    </div>
    <?php echo $this->formend(); ?>
</div>