<div class="row">
    <?php
        if(count($this->message) > 0)
        {
            echo "<div class=\"small-12 columns\">";
            echo "<div data-alert class=\"alert-box alert\">";
            foreach($this->message as $message)
            {
                echo $message;
            }
            echo "<a href=\"#\" class=\"close\">&times;</a></div>";
            echo "</div>";
        }
        echo $this->formstart();
    ?>
</div>
<div class="row">
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['date'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['inTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['outTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['lessTime'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <?php echo $this->fields['code'] ?>
    </div>
    <div class="small-12 medium-4 columns">
        <br>
        <?php echo $this->fields['submit'] ?>

    </div>
    <?php echo $this->formend(); ?>
</div>