<div class="row">
    <?php echo $this->formstart(); ?>
    <div class="small-6 medium-2 columns">
        <?php echo $this->fields['date'] ?>
    </div>
    <div class="small-6 medium-2 columns">
        <?php echo $this->fields['inTime'] ?>
    </div>
    <div class="small-6 medium-2 columns">
        <?php echo $this->fields['outTime'] ?>
    </div>
    <div class="small-6 medium-2 columns">
        <?php echo $this->fields['lessTime'] ?>
    </div>
    <div class="small-6 medium-2 columns">
        <?php echo $this->fields['code'] ?>
    </div>
    <div class="small-12 medium-2 columns">
        <br>
        <?php echo $this->fields['submit'] ?>
    </div>
    <?php echo $this->formend(); ?>
</div>