<?php
echo $this->formstart();
?>

<div class="panel radius" style="max-height:600px; overflow:auto;">
    <h3><i class="fa fa-plus"></i> New Request Form</h3>
    <hr>
    <?php

    if(count($this->errors) > 0)
    {
        if( isset($this->errors[0]))
        {
            if($this->errors[0]['label'] == 'Date Error')
            {
                echo "<div class='panel alert'>";
                foreach($this->errors as $error)
                {
                    foreach($error['errors'] as $message)
                    {
                        echo "<i class='fa fa-warning'></i> ".$message[0];
                    }
                }
                echo "</div>";
            }
        }
    }

    ?>
    <div class="row">
        <div class="small-12 medium-12 columns">
            <?php echo $this->fields['code'] ?>
        </div>
        <div class="small-12 medium-6 columns">
            <?php echo $this->fields['startDate'] ?>
        </div>
        <div class="small-12 medium-6 columns">
            <?php echo $this->fields['endDate'] ?>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <?php echo $this->fields['note'] ?>
        </div>
    </div>
    <div class="row">
        <div class="small-4 columns">
            &nbsp;
        </div>

        <div class="small-4 columns">
            <?php echo $this->fields['submit'] ?>
        </div>

        <div class="small-4 columns">
            &nbsp;
        </div>
    </div>
    <?php echo $this->formend(); ?>
</div>
<script>
    <?php
    $date = new DateTime();

    if($date->format('d') > 25)
    {
        $date->modify('first day of next month');
        $date->modify('+25 days');
    }

    $date->modify("+1 year");
    $maxDate = $date->setDate($date->format('Y'),$date->format('m'),25)->format('m/d/Y');
    $date->modify("-1 year");

    $minDate = $date->modify('-1 month +1 day');
    $minDate = $date->format('m/d/Y');
    ?>

    $(document).ready(function() {
        $(function() {
            $( "#startDate" ).datepicker({
                numberOfMonths:2,
                inline: true,
                minDate: "<?php echo $minDate ?>",
                maxDate: "<?php echo $maxDate ?>",
                showWeek: true,
                showButtonPanel: true
            });

            $( "#endDate" ).datepicker({
                numberOfMonths:2,
                inline: true,
                minDate: "<?php echo $minDate ?>",
                maxDate: "<?php echo $maxDate ?>",
                showWeek: true,
                showButtonPanel: true
            });
        });

        $('#entryToggle').click(function()
        {
            if($('#entryForm').is(":visible"))
            {
                $('#entryToggleIcon').addClass('fa-chevron-circle-down');
                $('#entryToggleIcon').removeClass('fa-chevron-circle-up');
                $('#entryToggleText').html('Show');
            }
            else
            {
                $('#entryToggleIcon').addClass('fa-chevron-circle-up');
                $('#entryToggleIcon').removeClass('fa-chevron-circle-down');
                $('#entryToggleText').html('Hide')
            }
            $('#entryForm').slideToggle(400);
        });


    });
</script>
