<?php echo $this->formstart(); ?>
    <div class="row">
        <div class="small-6 columns">
            <?php echo $this->fields['account'] ?>
        </div>
        <div class="small-6 columns">
            <?php echo $this->fields['year'] ?>
        </div>
        <div class="small-12 columns">
            <?php echo $this->fields['submit'] ?>
        </div>
    </div>
<?php echo $this->formend(); ?>