<div class="section">
    <div class="row">
            <div class="small-12 medium-8 medium-push-2 columns">
                <?php
                    if(count($this->form) > 0)
                    {
                        echo $this->form;
                    }
                    else
                    {
                        echo "
                            <div class='text-center'>
                            <h1>Confirmation</h1>
                            <p>Please confirm the following request</p>
                            </div>
                        ";

                        echo "
                            <div class='panel white radius'>
                            <div class='row'>
                                <div class='small-12 columns text-center'>
                                    <h3>".$this->request['codeName']." Request</h3>
                                </div>
                            </div>
                            <div class='row'>
                                <div class='small-12 columns'>
                                    <table width='100%'>
                                        <tr>
                                            <td><b>From:</b> ".date("l, F jS Y",strtotime($this->request['startDate']))."</td>
                                            <td><b>To:</b> ".date("l, F jS Y",strtotime($this->request['endDate']))."</td>
                                        </tr>
                                        <tr>
                                            <td><b>Type:</b> ".$this->request['codeName']."</b></td>
                                            <td><b>Hours:</b> ".$this->request['totalHoursRequested']."</td>
                                        </tr>
                                        <tr>
                                            <td colspan='2'>
                                            <b>Note:</b><br><br>
                                            ".$this->request['note']."
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <div class='row'>
                                <div class='small-12 columns'>
                                    <table width='100%'>
                                        <tr>
                                            <th colspan='4' class='text-center'>
                                                <h5><b>Times</b></h5>
                                                ";
                                                if($this->userType == "full")
                                                {
                                                    echo "<p>All hours are calculated to the nearest half hour.</p>";
                                                }
                                                echo "
                                            </th>
                                        </tr>
                                        ";

                                    if($this->userType == "full")
                                    {
                                        echo "
                                        <tr>
                                               <th>Date</th>
                                               <th>Start Time</th>
                                               <th>End Time</th>
                                               <th>Hours Requested</th>
                                        </tr>
                                        ";
                                    }
                                    else
                                    {
                                        echo "
                                        <tr>
                                               <th>Date</th>
                                               <th>Hours Requested</th>
                                        </tr>
                                        ";
                                    }

                                    if(count($this->request['dateTimes']) > 0)
                                    {
                                        foreach($this->request['dateTimes'] as $day)
                                        {
                                            $name = $day['dateString'];
                                            $hours = $day['hoursRequested'];
                                            if($this->userType == "full")
                                            {
                                                $start = $day['times']['startTime'];
                                                $end = $day['times']['endTime'];
                                                echo "
                                                    <tr>
                                                        <td>$name</td>
                                                        <td>$start</td>
                                                        <td>$end</td>
                                                        <td>$hours</td>
                                                    </tr>
                                                ";
                                            }
                                            else
                                            {
                                                echo "
                                                    <tr>
                                                        <td>$name</td>
                                                        <td>$hours</td>
                                                    </tr>
                                                ";
                                            }
                                        }
                                    }
                                    echo "</table>";
                                echo"</div>
                            </div>
                            <div class='row'>
                                <div class='small-6 columns'>
                                    <a class='button radius expand alert' href='".$this->link(array('requests','remove',$this->request['requestId']))."'><i class='fa fa-close'></i> Cancel</a>
                                </div>
                                <div class='small-6 columns'>
                                    <a class='button radius expand success' href='".$this->link(array('requests','submit',$this->request['requestId']))."'><i class='fa fa-check'></i> Submit</a>
                                </div>
                            </div>
                            </div>
                        ";
                    }
                ?>
            </div>
        </div>
    </div>
</div>
