<div class="section">
    <div class="row">
        <div class="small-6 columns">
            <h1><i class="fa fa-check-square"></i> Request Declension</h1>
        </div>
        <div class="small-6 columns text-right">
            <a href="<?php echo $this->link(array("requests"))?>" class="button radius"><i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <p>Please provide an explanation for declension:</p>
            <?php echo $this->form ?>
        </div>
    </div>
</div>

