<div class="section">
    <div class="row">
        <div class="small-6 columns">
            <h1><i class="fa fa-check-square"></i> Requests</h1>
        </div>
        <div class="small-6 columns text-right">

        </div>
    </div>
    <div class="row">
        <div class="small-6 columns">
            <?php echo $this->form ?>
        </div>
        <div class="small-6 columns">
            <h3>Current Requests</h3>
        </div>
    </div>
</div>
