<div class="section">
    <div class="row">
        <div class="small-6 columns">
            <h1><i class="fa fa-check-square"></i> Requests</h1>
        </div>
        <div class="small-6 columns text-right">
            <ul class="button-group radius">
                <li><a href="#" class="button" data-reveal-id="newRequest"><i class="fa fa-plus"></i> New Request</a></li>
                <?php
                    $user = new userModel();
                    if($user->getAuthLevel() == 900)
                    {
                        echo "<li><a href=\"".$this->link(array('requests','all'))."\" class=\"button\"><i class=\"fa fa-list\"></i> All Staff Requests</a></li>";
                    }
                ?>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <h3>Your Requests</h3>
            <?php

            if(count($this->requests) > 0)
            {
                echo "
                    <table width='100%'>
                       <tr>
                           <th>Type</th>
                           <th>Requested On</th>
                           <th>Start Date</th>
                           <th>End Date</th>
                           <th>Total Hours</th>
                           <th>Status</th>
                           <th>Note</th>
                           <th></th>
                       </tr>
                ";
                foreach($this->requests as $request)
                {
                    echo "
                        <tr>
                            <td>
                                    <a class='' href='".$this->link(array("requests","request",$request['requestId']))."'><i class='fa fa-file'></i> ".$request['codeName']."</a>                                
                            </td>
                            <td>
                                ".date("l",strtotime($request['dateOfRequest']))."<br>
                                ".date("M. jS Y",strtotime($request['dateOfRequest']))."
                            </td>
                            <td>
                                ".date("l",strtotime($request['startDate']))."<br>
                                ".date("M. jS Y",strtotime($request['startDate']))."
                            </td>
                            <td>
                                ".date("l",strtotime($request['endDate']))."<br>
                                ".date("M. jS Y",strtotime($request['endDate']))."
                            </td>
                            <td>".$request['totalHoursRequested']."</td>
                        ";
                            if($request['status'] == "0")
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending approval</td>";
                            }
                            elseif($request['status'] == "1")
                            {
                                echo "<td><i class='fa fa-check'></i> Approved by ".$request['approvedByName']['firstName']." ".$request['approvedByName']['lastName']."</td>";
                            }
                            elseif($request['status'] == "2")
                            {
                                echo "<td><i class='fa fa-close'></i> Declined by ".$request['approvedByName']['firstName']." ".$request['approvedByName']['lastName']."</td>";
                            }
                            elseif($request['status'] == "3")
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending notification</td>";
                            }
                            else
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                            }

                            echo "
                                <td><a href='#' class='viewNote'>View</a></td>
                            ";

                            if($request['status'] == 0 || $request['status'] == 3)
                            {
                                echo "<td><a href=\"".$this->link(array('requests','remove',$request['requestId']))."\" class='red'><i class='fa fa-trash'></i> Remove</a></td>";
                            }
                            else
                            {
                                echo "<td><i class='fa fa-lock'></i> Locked</td>";
                            }
                    echo "
                          
                        </tr>
                        <tr class='note' style='display:none;'>
                            <td colspan='8'>
                                <b>Note:</b> ".$request['note']."
                            </td>
                        </tr>
                    ";
                }
                echo "</table>";
            }

            ?>
        </div>
    </div>

            <?php

            if(count($this->staffRequests) > 0)
            {
                echo "
                    <div class=\"row\">
                        <div class=\"small-12 columns\" style=\"max-height:800px; overflow:auto;\">
                            <h3>Your Staff Requests</h3>
                ";

                echo "
                <table width='100%'>
                   <tr>
                       <th>Staff</th>
                       <th>Type</th>
                       <th>Requested On</th>
                       <th>Start Date</th>
                       <th>End Date</th>
                       <th>Total Hours</th>
                       <th>Status</th>
                       <th></th>
                   </tr>
            ";
                foreach($this->staffRequests as $request)
                {
                    echo "
                    <tr>
                        <td>
                            <a class='' href='".$this->link(array("requests","request",$request['requestId']))."'><i class='fa fa-file'></i> ".$request['firstName']." ".$request['lastName']."</a>
                        </td>
                        <td>
                                ".$request['codeName']."</a>                                
                        </td>
                        <td>
                            ".date("l",strtotime($request['dateOfRequest']))."<br>
                            ".date("M. jS Y",strtotime($request['dateOfRequest']))."
                        </td>
                        <td>
                            ".date("l",strtotime($request['startDate']))."<br>
                            ".date("M. jS Y",strtotime($request['startDate']))."
                        </td>
                        <td>
                            ".date("l",strtotime($request['endDate']))."<br>
                            ".date("M. jS Y",strtotime($request['endDate']))."
                        </td>
                        <td>".$request['totalHoursRequested']."</td>
                        
                    ";

                    if($request['status'] == "0")
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                    }
                    elseif($request['status'] == "1")
                    {
                        echo "<td><i class='fa fa-check'></i> Approved</td>";
                    }
                    elseif($request['status'] == "2")
                    {
                        echo "<td><i class='fa fa-close'></i> Declined</td>";
                    }
                    elseif($request['status'] == "3")
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending notification</td>";
                    }
                    else
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                    }

                    if($request['status'] == 0 || $request['status'] == 3)
                    {
                        echo "<td style='width:205px;'>
                                <br>
                                <ul class='button-group'>
                                    <li><a class='button tiny success' href=\"".$this->link(array('requests','approve',$request['requestId']))."\" class='green'><i class='fa fa-check'></i> Approve</a></li>
                                    <li><a class='button tiny alert' href=\"".$this->link(array('requests','decline',$request['requestId']))."\" class='red'><i class='fa fa-close'></i> Decline</a></li>
                                </ul>
                            </td>";
                    }
                    else
                    {
                        echo "<td><i class='fa fa-lock'></i> Locked</td>";
                    }
                    echo "
                      
                    </tr>
                    <tr>
                        <td colspan='8' style='border-bottom:1px #ddd solid'>
                            <b>Requester Note:</b> " .$request['note']."<br><br>
                            <b>Supervisor Note:</b> " .$request['superNote']."
                        </td>
                    </tr>
                ";
                }
                echo "</table></div></div>";
            }

            ?>
</div>

<div id="newRequest" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <?php echo $this->form ?>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php

if($this->formError == 1)
{
    echo "<script>";
    echo "$('#newRequest').foundation('reveal','open');";
    echo "</script>";
}

?>

<script>

    $(window).ready(function() {
        $('.viewNote').click(function(e) {
            $(this).parent().parent().next('.note').toggle();
            e.preventDefault();
        });
    });

</script>