<div class="section">
    <div class="row">
        <div class="small-4 columns">
            <h1><i class="fa fa-check-square"></i> Requests</h1>
        </div>
        <div class="small-8 columns text-right">
            <ul class="button-group radius">
                <li><a href="#" class="button small success" data-reveal-id="newRequest"><i class="fa fa-plus"></i> New Request</a></li>
                <li><a href="#" class="button small " data-reveal-id="policy"><i class="fa fa-file"></i> Policy</a></li>
                <li><a href="<?php echo $this->link(array("requests","archive")) ?>" class="button small "><i class="fa fa-archive"></i> Your Archive</a></li>
                <?php

                    $user = new userModel();
                    if($user->getAuthLevel() >= 500)
                    {
                        echo "
                        <li><a href=\"".$this->link(array("requests","staffarchive"))."\" class=\"button small \"><i class=\"fa fa-archive\"></i> Staff Archive</a></li>
                        ";
                    }

                ?>

            </ul>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <h3>Your Requests for Leave</h3>
            <?php

            if(count($this->requests) > 0)
            {
                echo "
                    <table width='100%'>
                       <tr>
                           <th>Type</th>
                           <th>Requested On</th>
                           <th>Start Date</th>
                           <th>End Date</th>
                           <th>Total Hours</th>
                           <th>Status</th>
                           <th></th>
                       </tr>
                ";
                foreach($this->requests as $request)
                {
                    echo "
                        <tr>
                            <td>
                                <a class='' href='".$this->link(array("requests","request",$request['requestId']))."'><i class='fa fa-file'></i> ".$request['codeName']."</a>                                
                            </td>
                            <td>
                                ".date("l",strtotime($request['dateOfRequest']))."<br>
                                ".date("M. jS Y",strtotime($request['dateOfRequest']))."
                            </td>
                            <td>
                                ".date("l",strtotime($request['startDate']))."<br>
                                ".date("M. jS Y",strtotime($request['startDate']))."
                            </td>
                            <td>
                                ".date("l",strtotime($request['endDate']))."<br>
                                ".date("M. jS Y",strtotime($request['endDate']))."
                            </td>
                            <td>".$request['totalHoursRequested']."</td>
                        ";
                            if($request['status'] == "0")
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending approval</td>";
                            }
                            elseif($request['status'] == "1")
                            {
                                echo "<td style='color:green;'><i class='fa fa-check'></i> Approved by ".$request['approvedByName']['firstName']." ".$request['approvedByName']['lastName']."</td>";
                            }
                            elseif($request['status'] == "2")
                            {
                                echo "<td style='color:orangered;'><i class='fa fa-close'></i> Declined by ".$request['approvedByName']['firstName']." ".$request['approvedByName']['lastName']."</td>";
                            }
                            elseif($request['status'] == "3")
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending notification</td>";
                            }
                            elseif($request['status'] == "4")
                            {
                                echo "<td style='color:red;'><i class='fa fa-warning'></i> Cancelled</td>";
                            }
                            else
                            {
                                echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                            }

                            if($request['status'] == 0 || $request['status'] == 3)
                            {
                                echo "<td><a href=\"".$this->link(array('requests','remove',$request['requestId']))."\" class='red'><i class='fa fa-trash'></i> Remove</a></td>";
                            }
                            else
                            {
                                echo "<td><i class='fa fa-lock'></i> Locked</td>";
                            }
                }
                echo "</table>";
            }
            else
            {
                echo "
                    <div class='panel radius text-center'>
                        <p>-No requests-</p>
                    </div>
                ";
            }

            ?>
        </div>
    </div>

            <?php
            if($this->authLevel >= 500)
            {
                echo "
                <div class=\"row\">
                    <div class=\"small-12 columns\">
                        <h3>Your Staff Requests for Leave</h3>";
            }

            if(count($this->staffRequests) > 0)
            {
                echo "
                    <table width='100%'>
                       <tr>
                           <th>Staff</th>
                           <th>Type</th>
                           <th>Requested On</th>
                           <th>Start Date</th>
                           <th>End Date</th>
                           <th>Total Hours</th>
                           <th>Status</th>
                           <th></th>
                       </tr>
                ";
                foreach($this->staffRequests as $request)
                {
                    echo "
                    <tr>
                        <td>
                            <a class='' href='".$this->link(array("requests","request",$request['requestId']))."'><i class='fa fa-file'></i> ".$request['firstName']." ".$request['lastName']."</a>
                        </td>
                        <td>
                                ".$request['codeName']."</a>                                
                        </td>
                        <td>
                            ".date("l",strtotime($request['dateOfRequest']))."<br>
                            ".date("M. jS Y",strtotime($request['dateOfRequest']))."
                        </td>
                        <td>
                            ".date("l",strtotime($request['startDate']))."<br>
                            ".date("M. jS Y",strtotime($request['startDate']))."
                        </td>
                        <td>
                            ".date("l",strtotime($request['endDate']))."<br>
                            ".date("M. jS Y",strtotime($request['endDate']))."
                        </td>
                        <td>".$request['totalHoursRequested']."</td>   
                    ";

                    if($request['status'] == "0")
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                    }
                    elseif($request['status'] == "1")
                    {
                        echo "<td><i class='fa fa-check'></i> Approved</td>";
                    }
                    elseif($request['status'] == "2")
                    {
                        echo "<td><i class='fa fa-close'></i> Declined</td>";
                    }
                    elseif($request['status'] == "3")
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending notification</td>";
                    }
                    elseif($request['status'] == "4")
                    {
                        echo "<td style='color:red;'><i class='fa fa-warning'></i> Cancelled</td>";
                    }
                    else
                    {
                        echo "<td><i class='fa fa-refresh'></i> Pending</td>";
                    }

                    if($request['status'] == 0 || $request['status'] == 3)
                    {
                        echo "<td style='width:205px;'>
                                <br>
                                <ul class='button-group'>
                                    <li><a class='button tiny success' href=\"".$this->link(array('requests','approve',$request['requestId']))."\" class='green'><i class='fa fa-check'></i> Approve</a></li>
                                    <li><a class='button tiny alert' href=\"".$this->link(array('requests','decline',$request['requestId']))."\" class='red'><i class='fa fa-close'></i> Decline</a></li>
                                </ul>
                            </td>";
                    }
                    elseif($request['status'] == 1)
                    {
                        echo "<td>
                                <br>
                                <ul class='button-group'>
                                    <li><a class='button tiny warning' href=\"".$this->link(array('requests','cancel',$request['requestId']))."\" class='warning'><i class='fa fa-close'></i> Cancel</a></li>
                                </ul>
                            </td>";
                    }
                    else
                    {
                        echo "<td><i class='fa fa-lock'></i> Locked</td>";
                    }
                    echo "
                      
                    </tr>
                    <tr>
                        <td colspan='8' style='border-bottom:1px #ddd solid'>
                            <b>Requester Note:</b> " .$request['note']."<br><br>
                            <b>Supervisor Note:</b> " .$request['superNote']."
                        </td>
                    </tr>
                ";
                }
                echo "</table>";
                echo "</div></div>";
            }
            else
            {
                if($this->authLevel >= 500)
                {
                    echo "
                        <div class='row'>
                            <div class='small-12 column'>
                                <div class='panel radius text-center'>
                                    <p>-No requests-</p>
                                </div>
                            </div>
                        </div>  
                    ";
                }
            }


            ?>
</div>

<div id="newRequest" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <?php echo $this->form ?>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="policy" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <h1>Request for Leave</h1>
    <p>As per the Twin Falls Public Library Personnel Policy, paid Vacation & Sick leave are available only to full-time employees with benefits.</p>
    <p>Part-time employees may ask for vacation or sick time off without pay & upon approval of their immediate supervisor</p>
    <p>Vacation or Sick leave, per this policy, is to be scheduled with consent of the responsible department supervisor. They will then put this information on the "GONE CALENDAR".</p>
    <p>Each employee is required to submit a "Request for Leave" form. Your immediate Supervisor and Director will then determine the appropriateness of the dates in accordance with scheduling.</p>
    <p><b><u>As a courtesy to fellow employees, and for scheduling arrangements, please submit requests two weeks in advance for vacation time, leave of absence, and military leave. For sick time, notify your supervisor as soon as possible and submit a Request for Leave form.</u></b></p>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<?php

if($this->formError == 1)
{
    echo "<script>";
    echo "$('#newRequest').foundation('reveal','open');";
    echo "</script>";
}

?>

<script>

    $(window).ready(function() {
        $('.viewNote').click(function(e) {
            $(this).parent().parent().next('.note').toggle();
            e.preventDefault();
        });
    });

</script>