<div class="section">
    <div class="row">
        <div class="small-6 columns">
                <h1><i class="fa fa-file"></i> Request Details</h1>
        </div>
        <div class="small-6 columns text-right">
            <a class="button radius secondary" href="<?php echo $this->link(array("requests")) ?>"><i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <hr>
        </div>
    </div>
    <div class='row'>
        <div class="small-3 columns">
            <b>Requester</b><br>
            <?php echo $this->firstName ?> <?php echo $this->lastName ?><br><br>
        </div>
        <div class="small-3 columns">
            <b>Type</b><br>
            <?php echo $this->codeName ?><br><br>
        </div>
        <div class="small-3 columns">
            <b>Total Hours Requested</b><br>
            <?php echo $this->totalHoursRequested ?><br><br>
        </div>
        <div class="small-3 columns">
            <b>Status</b><br>
            <?php

            if($this->status == "0")
            {
                echo "Pending approval";
            }
            elseif($this->status == "1")
            {
                echo "Approved";
            }
            elseif($this->status == "2")
            {
                echo "Declined";
            }
            elseif($this->status == "3")
            {
                echo "Pending notification";
            }
            else
            {
                echo "Pending";
            }

            ?>
        </div>
    </div>
    <div class="row">
        <div class="small-3 columns">
            <b>Requested On</b><br>
            <?php echo $this->requestDate ?>
        </div>
        <div class="small-3 columns">
            <b>Request Start Date</b><br>
            <?php echo $this->startDate ?>
        </div>
        <div class="small-3 columns">
            <b>Request End Date</b><br>
            <?php echo $this->endDate ?><br><br>
        </div>
        <div class="small-3 columns">
            <b>Assigned Supervisor</b><br>
            <?php echo $this->approvedBy ?><br><br>
        </div>
    </div>
    <div class="row">
        <div class="small-6 columns">
            <b>Requester Note</b><br>
            <?php echo $this->note ?><br><br>
        </div>
        <div class="small-6 columns">
            <b>Supervisor Note</b><br>
            <?php echo $this->superNote ?><br><br>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <b>Request Details</b><br>
            <table width="100%">
                <tr>
                    <th>Date</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Hours Requested</th>
                </tr>
            <?php
                if(count($this->dateTime) > 0)
                {
                    foreach($this->dateTime as $date)
                    {
                        echo "
                        <tr>
                            <td>".$date->dateString."</td>
                            <td>".$date->times->startTime."</td>
                            <td>".$date->times->endTime."</td>
                            <td>".$date->hoursRequested."</td>
                        </tr>
                        ";
                    }
                }

            ?>

            </table>
        </div>
    </div>
</div>
