<style>
    table {
        border:1px solid #ccc;
    }

    th {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
        background-color: #eaeaea;
    }

    td {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
    }

</style>
<table width="100%" style="border:0px; padding:0px; margin:0px;">
    <tr>
        <td style="border:0px;">
            <h3><i class="fa fa-clock-o"></i> Total Hours: <?php echo $this->date ?></h3>

        </td>
        <td style="border:0px;" class="text-right">
            <br>
            <p>
                (-) No time entry.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                (*) Paycode other than 'Normal' was used.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                (<i class="fa fa-sticky-note"></i>) Approved time off request submitted.
            </p>
            <p class="hide-for-print">
                (<i class="fa fa-square" style="color:#e2413b;"></i>) Request for leave required.
                (<i class="fa fa-square" style="color:#e4a030;"></i>) Request for leave without timesheet entry.
                (<i class="fa fa-square" style="color:#f1e96d;"></i>) Request for leave with normal paycode entry.
            </p>
        </td>
    </tr>
</table>
<table width="100%" id="report">
    <thead>
    <tr>
        <th></th>
        <?php

        $previousDate = explode("-",$this->previousDate);

        $date = new DateTime();
        $date->setDate($previousDate[0],$previousDate[1],$previousDate[2]);

        $date->setTime(0,0,0);

        for($i=1;$i<=$this->span;$i++)
        {
            if($date->format('d') >= 26)
            {
                echo "<th style='background-color:#fff;border-bottom:1px solid #ccc; '>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }
            else
            {
                echo "<th style='border-bottom:1px solid #ccc;'>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }

            $date->modify('+1 day');
        }
        ?>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach($this->report as $user=>$dates)
    {
        $totalTime = array_sum($dates);
        echo "<tr>";
        echo "<td style='border-bottom:1px solid #ccc;'><b>$user</b><br>Total: $totalTime</td>";

        $date = new DateTime();

        if($this->month == "01")
        {
            $date->setDate($this->previousYear,$this->previousMonth,26);
        }
        else
        {
            $date->setDate($this->year,$this->previousMonth,26);
        }

        for($j=1;$j<=$this->span;$j++)
        {
            echo "<td class='text-center' style='border-bottom:1px solid #ccc;'>";
            $value = "-&nbsp;";
            foreach ($dates as $entryDate => $total)
            {
                $newDate = explode("-", $entryDate);
                $dayOfMonth = $newDate[2];

                if($dayOfMonth == $date->format('d'))
                {
                    //Displays an icon if some of the time for this day is not a normal pay code.
                    $pos = strpos($total, '*');
                    if($pos !== False)
                    {
                        echo "<span class=\"otherCodeTag\">*</span>";
                    }

                    $value = str_replace("*","",$total);
                    $value = $value."&nbsp;";
                }
            }
            echo "<span class=\"valueTag\">$value</span>";

            //Check for requests on this day
            foreach($this->requests as $request)
            {
                //print_r($request);
                $userInfo = new userModel();
                $staff = $userInfo->userInfo($request['userId']);
                $firstName = $staff['firstName'];
                $lastName = $staff['lastName'];
                $name = $lastName.", ".$firstName;
                $requestDays = $request['dateTimes'];

                $requestDates = array();

                foreach($requestDays as $day)
                {
                    $z = new DateTime();
                    $z->setTimestamp($day->date);
                    $requestDates[] = $z->format("m/d/Y");
                }

                if(in_array($date->format('m/d/Y'),$requestDates) && $name == $user)
                //if($date->format('m/d/Y') >= $request['startDate'] && $date->format('m/d/Y') <= $request['endDate'] && $name == $user)
                {
                    $startDate = $request['startDate'];
                    $endDate = $request['endDate'];
                    $codeName = $request['codeName'];
                    $status = $request['status'];
                    $totalHours = $request['totalHoursRequested'];

                    if($status == 1)
                    {
                        if ($startDate == $endDate) {
                            $msg = "$codeName request for $startDate for $totalHours hours.";
                        } else {
                            $msg = "$codeName request from $startDate to $endDate for $totalHours hours.";
                        }

                        echo "<span class='requestTag'><i class='fa fa-sticky-note'></i></span>";
                    }
                }
            }

            echo "</td>";

            $date->modify('+1 day');
        }
        echo "</tr>";
    }
    ?>
    </tbody>
</table>
<script>
    $(window).ready(function() {
        $("#report").find('td').each(function() {
            $v = $(this).html();
            $otherCodeTag = 0;
            $valueTag = 0;
            $requestTag = 0;

            if($otherCodeValue = $(this).find(".otherCodeTag").html() == '*')
            {
                $otherCodeTag = 1;
            }

            if($otherCodeValue = $(this).find(".valueTag").html() != '-&nbsp;')
            {
                $valueTag = 1;
            }

            //console.log($(this).find(".requestTag").html());
            if($requestTagValue = $(this).find(".requestTag").html() == '<i class="fa fa-sticky-note"></i>')
            {
                $requestTag = 1;
            }

            //Highlight the cell if a not normal paycode submitted without a request for leave.
            if($otherCodeTag == 1 && $requestTag == 0)
            {
                $(this).css("background-color","#e2413b");
                $(this).css("color","white");
            }

            //Highlight the cell if a normal paycode was submitted with a request for leave.
            if($otherCodeTag == 0 && $requestTag == 1 && $valueTag == 1)
            {
                $(this).css("background-color","#f1e96d");
            }

            //Highlight the cell if request for leave submitted but no time submitted
            if($requestTag == 1 && $valueTag == 0)
            {
                $(this).css("background-color","#e4a030");
            }

        });
    });

</script>