<style>
    table {
        border:1px solid #ccc;
    }

    th {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
        background-color: #eaeaea;
    }

    td {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
    }

</style>
<table width="100%" style="border:0px; padding:0px; margin:0px;">
    <tr>
        <td style="border:0px;"><h3><i class="fa fa-clock-o"></i> Total Hours: <?php echo date("F",$this->month) ?> <?php echo $this->year ?></h3></td>
        <td style="border:0px;" class="text-right"><?php echo $this->startDate ?> - <?php echo $this->endDate ?></td>
    </tr>
</table>
<table width="100%">
    <thead>
    <tr>
        <th></th>
        <?php

        $date = new DateTime();
        $date->setDate($this->year,$this->previousMonth,26);

        for($i=1;$i<=$this->span;$i++)
        {
            if($date->format('d') >= 26)
            {
                echo "<th style='background-color:#fff;border-bottom:1px solid #ccc; '>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }
            else
            {
                echo "<th style='border-bottom:1px solid #ccc;'>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }
            $date->modify('+1 day');
        }
        ?>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach($this->report as $user=>$dates)
    {
        $totalTime = array_sum($dates);
        echo "<tr>";
        echo "<td style='border-bottom:1px solid #ccc;'><b>$user</b><br>Total: $totalTime</td>";

        $date = new DateTime();
        $date->setDate($this->year,$this->previousMonth,26);
        for($j=1;$j<=$this->span;$j++)
        {
            echo "<td class='text-center' style='border-bottom:1px solid #ccc;'>";
            $value = "-";
            foreach ($dates as $entryDate => $total)
            {
                $newDate = explode("-", $entryDate);
                $dayOfMonth = $newDate[2];

                if($dayOfMonth == $date->format('d'))
                {
                    $value = $total;
                }
            }
            echo $value;
            echo "</td>";

            $date->modify('+1 day');
        }
        echo "</tr>";
    }
    ?>
    </tbody>
</table>
