<style>
    table {
        border:1px solid #ccc;
    }

    th {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
        background-color: #eaeaea;
    }

    td {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
    }

</style>
<table width="100%" style="border:0px; padding:0px; margin:0px;">
    <tr>
        <td style="border:0px;">
            <h3><i class="fa fa-clock-o"></i> Total Hours: <?php echo $this->date ?></h3>

        </td>
        <td style="border:0px;" class="text-right">
            <br>
            <p>
                (-) No time entry.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                (*) Paycode other than 'Normal' was used.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                (<i class="fa fa-sticky-note"></i>) Approved time off request submitted.
            </p>
        </td>
    </tr>
</table>
<table width="100%">
    <thead>
    <tr>
        <th></th>
        <?php

        $previousDate = explode("-",$this->previousDate);

        $date = new DateTime();
        $date->setDate($previousDate[0],$previousDate[1],$previousDate[2]);

        $date->setTime(0,0,0);

        for($i=1;$i<=$this->span;$i++)
        {
            if($date->format('d') >= 26)
            {
                echo "<th style='background-color:#fff;border-bottom:1px solid #ccc; '>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }
            else
            {
                echo "<th style='border-bottom:1px solid #ccc;'>".$date->format('D')."<br>".$date->format('n')."/".$date->format('j')."</th>";
            }

            $date->modify('+1 day');
        }
        ?>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach($this->report as $user=>$dates)
    {
        $totalTime = array_sum($dates);
        echo "<tr>";
        echo "<td style='border-bottom:1px solid #ccc;'><b>$user</b><br>Total: $totalTime</td>";

        $date = new DateTime();
        $date->setDate($this->year,$this->previousMonth,26);
        for($j=1;$j<=$this->span;$j++)
        {
            echo "<td class='text-center' style='border-bottom:1px solid #ccc;'>";
            $value = "-";
            foreach ($dates as $entryDate => $total)
            {
                $newDate = explode("-", $entryDate);
                $dayOfMonth = $newDate[2];

                if($dayOfMonth == $date->format('d'))
                {
                    $value = $total;
                    if(count($newDate) == 4)
                    {
                        //Displays an icon if some of the time for this day is not a normal pay code.
                        echo "*";
                    }
                }
            }
            echo $value;

            //Check for requests on this day
            foreach($this->requests as $request)
            {
                //print_r($request);
                $userInfo = new userModel();
                $staff = $userInfo->userInfo($request['userId']);
                $firstName = $staff['firstName'];
                $lastName = $staff['lastName'];
                $name = $lastName.", ".$firstName;

                if($date->format('m/d/Y') >= $request['startDate'] && $date->format('m/d/Y') <= $request['endDate'] && $name == $user)
                {
                    $startDate = $request['startDate'];
                    $endDate = $request['endDate'];
                    $codeName = $request['codeName'];
                    $status = $request['status'];
                    $totalHours = $request['totalHoursRequested'];

                    if($status == 1)
                    {
                        if ($startDate == $endDate) {
                            $msg = "$codeName request for $startDate for $totalHours hours.";
                        } else {
                            $msg = "$codeName request from $startDate to $endDate for $totalHours hours.";
                        }

                        echo "<i class='fa fa-sticky-note'></i>";
                    }
                }
            }

            echo "</td>";

            $date->modify('+1 day');
        }
        echo "</tr>";
    }
    ?>
    </tbody>
</table>
