
<style>
    table {
        border:1px solid #ccc;
    }

    th {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
        background-color: #eaeaea;
    }

    td {
        border:1px solid #ccc;
        padding:0px;
        margin:0px;
    }

    .scroll {
        overflow-x:scroll;
        overflow-y:visible;
    }

</style>
<table width="100%" style="border:0px; padding:0px; margin:0px;">
    <tr>
        <td style="border:0px;"><h3><i class="fa fa-clock-o"></i> Payroll Report: <?php echo date("F",$this->month) ?> <?php echo $this->year ?></h3></td>
        <td style="border:0px;" class="text-right"><?php echo $this->startDate ?> - <?php echo $this->endDate ?></td>
    </tr>
</table>
<table width="100%">
    <thead>
    <tr>
       <th style="width:150px;"></th>
       <?php

           foreach($this->codes as $code)
           {
               if($code == 'Normal')
               {
                   echo "<th style='background-color:#d8ffd3;'>$code</th>";
               }
               else
               {
                   echo "<th>$code</th>";
               }

           }

       ?>
    </tr>
    </thead>
    <tbody>
    <?php

    foreach($this->report as $user=>$codes)
    {

        echo "<tr>";
        echo "<td style='border-bottom:1px solid #ccc;'><b>$user</b></td>";

        //for($j=1;$j<=count($this->codes);$j++)
        foreach($this->codes as $id=>$timeCode)
        {
            if($timeCode == 'Normal')
            {
                echo "<td class='text-center' style='background-color:#d8ffd3; border-bottom:1px solid #ccc;'>";
            }
            else
            {
                echo "<td class='text-center' style='border-bottom:1px solid #ccc;'>";
            }
            $value = "-";
            foreach ($codes as $code => $total)
            {
                if($timeCode == $code)
                {
                    $value = $total;
                }
            }
            echo $value;
            echo "</td>";
        }
        echo "</tr>";
    }
    ?>
    </tbody>
</table>
