<div class="section">
    <div class="row">
        <div class="small-12 columns">
            <h1><i class="fa fa-file"></i>Time Sheet Review <small>Active</small></h1>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <ul class="button-group radius right">
                <li><a class='button secondary' href="<?php echo $this->link(array('reports',$this->year,$this->month)) ?>">Back</a></li>
            </ul>
        </div>
        <div class="small-12 columns text-center">
            <div data-alert class="alert-box alert">
                <i class="fa fa-warning"></i> <?php echo $this->errorMessage ?>
                <a href="#" class="close">&times;</a>
            </div>
        </div>
    </div>
</div>
