<div class="section">
    <div class="row">
        <div class="small-12 columns">
            <h1><i class="fa fa-unlock"></i> Time Unlock</h1>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns text-center">
            <div class="panel">
            <?php echo $this->message ?>
            </div>
        </div>
        <div class="small-12 columns text-center">
            <a class="button secondary" href="<?php echo $this->link(array('reports','unlock')) ?>">Back</a>
        </div>
    </div>
</div>

