<?php echo $this->doctype; ?>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo $this->title; ?></title>
        <?php
            $this->metas();
            $this->styles();
            $this->scripts();
        ?>
    </head>
    <body>
        <div class="header">
            <div class="row">
                <div class="small-12 column text-center">
                    <h1><i class="fa fa-clock-o"></i> TimeTracker</h1>
                </div>
            </div>
        </div>
        <div class="section">
            <?php $this->content(); ?>
        </div>
        <script>$(document).foundation();</script>
    </body>
</html>
